title: Geremy Paige
email: geremypaige123@gmail.com
description: >-
   AI & Cybersecurity Specialist with expertise in risk management, compliance, and competitive intelligence.

baseurl: "" # Update to match the repository name
url: "https://gpaige123.github.io" # Base GitHub Pages URL


github:  gpaige123

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
