title: Geremy Paige - ePortfolio
email: your-email@example.com
description: >-
  Welcome to my ePortfolio! This site showcases my projects, skills, and experience.

baseurl: "" # Update to match the repository name
url: "https://gpaige123.github.io" # Base GitHub Pages URL

twitter_username: gpaige123
github_username:  gpaige123

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
